In [8]:
#1-Dimensional array
import numpy as np
a= np.array([1,2,3,4,5,6,7])
print (a)

print(np.arange(10))
print(np.array(range(2,20,2)))


AttributeError: module 'numpy' has no attribute 'max'

In [17]:
a.ndim


1

In [1]:
a.shape


NameError: name 'a' is not defined

In [19]:
len(a)

7

In [24]:
#2-d array or list in list
b= np.array([[0,1,2],[4,5,6]])
b

array([[0, 1, 2],
       [4, 5, 6]])

In [25]:
b.ndim


2

In [26]:
b.shape

(2, 3)

In [9]:
#3-d array OR list in list in list
c=np.array([[[0,1],
            [2,3]],
            
            [
                [4,5],
                [6,7]
            ]]
             )
c

AttributeError: module 'numpy' has no attribute 'max'

In [28]:
c.ndim

3

In [29]:
c.shape   #(2,2,2) means 2 rows 2 columns and depth of 2

(2, 2, 2)

In [30]:
a= np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [31]:
a= np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
b= np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [34]:
#for identity matrix
a= np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#diagnol matrix or diagnol array
a= np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [39]:
a= np.random.rand(4)
print (a)
a.dtype

[0.34162482 0.29725297 0.26689707 0.99366707]


dtype('float64')

In [40]:
a = np.arange(10)
print(a[5])

5


In [44]:
a= np.diag([1,2,3,4])
print(a[2,3])
print(a[2,2])
a[2,2]=5
print(a[2,2])
a

0
3
5


array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 4]])

In [47]:
a=np.arange(10)
a

#now to create subarray starting from 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#now to create subarray starting from 
a[1:8:2]


array([1, 3, 5, 7])

In [51]:
#using boolean mask
a=np.random.randint(0,20,16)
a

array([13,  6,  6,  1, 16, 15, 15, 10,  7, 13, 16,  0,  5,  4,  9, 14])

In [55]:
masked = (a%3==0)#anything can be used in place of masked
b=a[masked]
b

array([ 6,  6, 15, 15,  0,  9])

In [58]:
#OPERATIONS ON NUMPY
a= np.arange(5)
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [61]:
a= np.arange(1,6)
b = np.ones(5) + 1
a-b    
    


array([-1.,  0.,  1.,  2.,  3.])

In [64]:
a= np.array([5,3,4,6,8])
b=np.array([6,2,3,9,10])
a>b

array([False,  True,  True, False, False])

In [66]:
#logical operation
a=np.array([1,0,1,1],dtype=bool)
b=np.array([0,0,1,1],dtype=bool)
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True False  True  True]
[False False  True  True]


In [69]:
#transcendental functin
a=np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [70]:
a=np.arange(5)
np.sum(a) #sums all elements of a

10

In [72]:
x= np.array([[1,2],[1,2]])
x

array([[1, 2],
       [1, 2]])

In [73]:
x.sum(axis=0)#column wise addition


array([2, 4])

In [74]:
x.sum(axis=1)#row wise addition


array([3, 3])

In [75]:
#logical operations
np.all([True,False,True,True])


False

In [76]:
np.all([True,False,False,False])


False

In [78]:
x=np.ones([5,5])
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [84]:
np.all(x==1)

True

In [85]:
np.any(x==0)

False

In [88]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
((a<=b)&(b<=c))

array([ True,  True,  True,  True])

In [89]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([9,10,11,12])
((a<=b)&(b<=c)).all()

True

In [94]:
data=np.loadtxt('populations.txt')
data
#data is stored in numpy array

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [98]:
populations= data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [101]:
#standard deviation of population
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [102]:
#species with highest population each year
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

In [104]:
#flatening or converting 2d into 1d array by using ravel function
a=np.array([[1,2,3],[7,4,6]])
a.ravel()

array([1, 2, 3, 7, 4, 6])

In [107]:
a=a.T #transpose
a


array([[1, 7],
       [2, 4],
       [3, 6]])

In [108]:
a.ravel()

array([1, 7, 2, 4, 3, 6])

In [111]:
#reshapping the flatening 
a=np.array([[1,2,3],[7,4,6]])
print(a.shape)
print(a)


(2, 3)
[[1 2 3]
 [7 4 6]]


In [113]:
b=a.ravel()
print(b)

[1 2 3 7 4 6]


In [115]:
#reshapping
b=b.reshape(2,3)
b

array([[1, 2, 3],
       [7, 4, 6]])

In [116]:
#3 dimensional matrix of size 4,3,2 i.e 4 matrices of 3 rows and 2 columns
a=np.arange(24).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [117]:
a[0,2,1]

5

In [121]:
#resizing
a=np.arange(4)
a.resize(8)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [123]:
#sorting along an axis
a=np.array([[2,1,3],[7,4,6]])
a.sort(axis=1)
a


array([[1, 2, 3],
       [4, 6, 7]])